import { readFile, readdir, stat } from "node:fs/promises";
import { isAbsolute, join, relative, resolve } from "node:path";
import { canonicalJson, sha256 } from "./hashing.js";
import type { DerivedBinding } from "./state.js";
import type { ProfileId } from "../types.js";

const DERIVED_OPERATORS = new Set(["mesh-simplify", "radial-fit", "course-regenerate", "axis-fit"]);

/** Canonical workspace-relative directory of generated phase modules. */
export const GENERATED_DIRECTORY = "model/.generated";
/** Pipeline-owned composition layer regenerated from current derivations; never agent-edited. */
export const GENERATED_REGISTRY_PATH = `${GENERATED_DIRECTORY}/registry.mjs`;
/** Canonical workspace-relative directory of agent-owned per-phase repair modules. */
export const REPAIRS_DIRECTORY = "model/repairs";

/**
 * Stable authored entry for DERIVED-mode projects: it never changes after initialization.
 * The pipeline composes phases by regenerating `.generated/registry.mjs`, which this entry
 * imports exactly once, so later derivations stay automatic without touching agent files.
 * A derived run verifies its canonical entry against this exact scaffold — replacing it is
 * a derived-lineage violation, not a builder option.
 */
export const MODEL_DERIVED_SCAFFOLD = `import { createGeneratedCandidate } from "./.generated/registry.mjs";

export function createCandidate() {
  return createGeneratedCandidate();
}
`;

/** Plain clean-room scaffold for INDEPENDENT-mode projects. */
export const MODEL_SCAFFOLD = `import * as THREE from "three";

export function createCandidate() {
  return new THREE.Group();
}
`;

export interface RepairModuleReference {
  phase: string;
  /** Workspace-relative path of the declarative repair spec (`model/repairs/<phase>.json`). */
  path: string;
}

/**
 * Tank articulation doctrine baked into the composition layer: the gun pivot rides under the
 * turret pivot so turretYaw physically carries the gun, matching the profile contract's
 * moving/stationary sets. Kept declarative and profile-scoped rather than name-guessed at
 * runtime across arbitrary subjects.
 */
const PROFILE_PIVOT_NESTING: Record<ProfileId, ReadonlyArray<readonly [string, string]>> = {
  tank: [["gun-pivot", "turret-pivot"]],
  generic: [],
};

const PROFILE_POSE_CONTROLS: Record<ProfileId, string> = {
  tank: [
    `      const turretPivot = root.getObjectByName("turret-pivot");`,
    `      if (turretPivot) turretPivot.rotation.y = p.turretYaw ?? 0;`,
    `      const gunPivot = root.getObjectByName("gun-pivot");`,
    `      if (gunPivot) gunPivot.rotation.x = p.gunElevation ?? 0;`,
  ].join("\n"),
  generic: "",
};

/**
 * Deterministically regenerates the pipeline-owned composition layer from the currently bound
 * derived phases, given in profile dependency order. Repair data is compiled INTO generated
 * phase modules by trusted derive, so the registry never imports builder-authored modules.
 * The authored entry imports this module exactly once, so later derivations rewire
 * automatically without touching agent files. Builders never author the registry.
 */
export function generateRegistrySource(profile: ProfileId, orderedPhases: ReadonlyArray<string>): string {
  const identifier = (phase: string): string => `createSeed${phase.replace(/[^a-z0-9]+/giu, "")}`;
  const lines: string[] = [];
  lines.push(`// Generated by mesh2threejs derive — trusted pipeline composition layer (do not edit by hand).`);
  lines.push(`import * as THREE from "three";`);
  for (const phase of orderedPhases) lines.push(`import { createSeed as ${identifier(phase)} } from "./${phase}.mjs";`);
  lines.push(``);
  lines.push(`function isDescendantOf(node, ancestor) {`);
  lines.push(`  let current = node.parent;`);
  lines.push(`  while (current) {`);
  lines.push(`    if (current === ancestor) return true;`);
  lines.push(`    current = current.parent;`);
  lines.push(`  }`);
  lines.push(`  return false;`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`const PIVOT_NESTING = [`);
  for (const [child, parent] of PROFILE_PIVOT_NESTING[profile]) lines.push(`  [${JSON.stringify(child)}, ${JSON.stringify(parent)}],`);
  lines.push(`];`);
  lines.push(``);
  lines.push(`export function createGeneratedCandidate() {`);
  lines.push(`  const root = new THREE.Group();`);
  lines.push(`  root.name = "candidate";`);
  for (const phase of orderedPhases) {
    const seed = identifier(phase);
    lines.push(`  root.add(${seed}());`);
  }
  // World-preserving reparent: seed modules emit pivots at WORLD coordinates, so
  // nesting a child pivot under its articulated parent must rebase the local
  // position by the parent's world origin or the geometry shifts and fails gates.
  lines.push(`  const childWorld = new THREE.Vector3();`);
  lines.push(`  const parentWorld = new THREE.Vector3();`);
  lines.push(`  for (const [childName, parentName] of PIVOT_NESTING) {`);
  lines.push(`    const child = root.getObjectByName(childName);`);
  lines.push(`    const parent = root.getObjectByName(parentName);`);
  lines.push(`    if (!child || !parent || child === parent) continue;`);
  lines.push(`    if (isDescendantOf(child, parent)) continue;`);
  lines.push(`    child.getWorldPosition(childWorld);`);
  lines.push(`    if (child.parent) child.removeFromParent();`);
  lines.push(`    parent.add(child);`);
  lines.push(`    parent.getWorldPosition(parentWorld);`);
  lines.push(`    child.position.set(childWorld.x - parentWorld.x, childWorld.y - parentWorld.y, childWorld.z - parentWorld.z);`);
  lines.push(`  }`);
  lines.push(`  return {`);
  lines.push(`    root,`);
  lines.push(`    setPose(pose) {`);
  lines.push(`      const p = pose ?? {};`);
  if (PROFILE_POSE_CONTROLS[profile]) lines.push(PROFILE_POSE_CONTROLS[profile]);
  lines.push(`    },`);
  lines.push(`  };`);
  lines.push(`}`);
  lines.push(``);
  return lines.join("\n");
}

/** Registry bytes for a fresh derived workspace with no derived phases yet. */
export function emptyGeneratedRegistry(profile: ProfileId): string {
  return generateRegistrySource(profile, []);
}

/**
 * Pipeline-owned provenance for one generated seed module. A manifest is candidate
 * provenance/configuration, not certification evidence: it exists so the audit can tell
 * trusted pipeline-generated geometry apart from hand-authored payloads, and so stale or
 * tampered artifacts fail closed against the current oracle preparation.
 */
export interface DerivationManifest {
  schemaVersion: 1;
  kind: "mesh2threejs-derived-seed";
  phase: string;
  oraclePreparationIdentity: string;
  preparedOracleHash: string;
  operator: "mesh-simplify" | "radial-fit" | "course-regenerate" | "axis-fit";
  recipe: Record<string, unknown>;
  inputGeometryHash: string;
  outputGeometryHash: string;
  /** Workspace-relative path of the generated module this manifest binds. */
  generatedModulePath: string;
  generatedModuleHash: string;
  inputTriangles: number;
  outputTriangles: number;
  /** Relative geometric error reported by the simplifier for the selected tier. */
  simplifierError?: number;
  /** Hash of the raw declarative repair spec bytes compiled into the generated module, if any. */
  repairSpecHash?: string;
  /** Number of declarative repair operations compiled into the generated module, if any. */
  repairOperations?: number;
}

/** Workspace directory holding derivation manifests, keyed one per generated module. */
export function derivedDirectory(internalRoot: string): string {
  return join(internalRoot, "derived");
}

export function derivationManifestHash(manifest: DerivationManifest): string {
  return sha256(canonicalJson(manifest));
}

function isDerivationManifest(value: unknown): value is DerivationManifest {
  if (!value || typeof value !== "object" || Array.isArray(value)) return false;
  const manifest = value as Partial<DerivationManifest>;
  return manifest.schemaVersion === 1
    && manifest.kind === "mesh2threejs-derived-seed"
    && typeof manifest.phase === "string"
    && typeof manifest.oraclePreparationIdentity === "string"
    && typeof manifest.preparedOracleHash === "string"
    && typeof manifest.operator === "string"
    && typeof manifest.inputGeometryHash === "string"
    && typeof manifest.outputGeometryHash === "string"
    && typeof manifest.generatedModulePath === "string"
    && typeof manifest.generatedModuleHash === "string"
    && Number.isFinite(manifest.inputTriangles)
    && Number.isFinite(manifest.outputTriangles);
}

export interface TrustedGeneratedModule {
  manifestPath: string;
  manifestHash: string;
  manifest: DerivationManifest;
}

export interface TrustedModuleAuthorityInput {
  /** Directory containing candidate derivation manifests (`<ws>/.mesh2threejs/derived`). */
  directory: string;
  workspaceRoot: string;
  /** Canonical preparation identity currently bound in workspace state. */
  preparationIdentity: string;
  /** Durable `state.derivedBindings`, written only by trusted derive code. */
  bindings: Record<string, DerivedBinding>;
  /** Builder phases for which a manifest may exist. */
  allowedPhases: ReadonlySet<string>;
}

/**
 * Loads every derivation manifest under `<workspace>/.mesh2threejs/derived` that carries FULL
 * five-way authority. A sidecar alone is not authority; all of the following must agree:
 *
 * 1. structurally valid manifest with a known operator;
 * 2. phase is a valid builder phase and module filename matches it canonically;
 * 3. generated path is workspace-relative AND resolves inside `<ws>/model/.generated/`
 *    (no absolute paths, no `..` or symlink escape);
 * 4. `oraclePreparationIdentity` equals the CURRENT bound preparation;
 * 5. durable state binding exists for the canonical module path, its manifest hash equals
 *    the recomputed manifest hash, its generated-module hash equals both the manifest's and
 *    the live file bytes', and its preparation identity equals the current one.
 *
 * Anything else is ordinary candidate source and receives the normal topology-dump audit.
 */
export async function loadTrustedGeneratedModules(input: TrustedModuleAuthorityInput): Promise<Map<string, TrustedGeneratedModule>> {
  const { directory, workspaceRoot, preparationIdentity, bindings, allowedPhases } = input;
  const trusted = new Map<string, TrustedGeneratedModule>();
  const canonicalGeneratedRoot = resolve(workspaceRoot, "model/.generated");
  let names: string[];
  try {
    names = await readdir(directory);
  } catch {
    return trusted;
  }
  const manifestsDirectory = resolve(directory);
  for (const name of names.filter((entry) => entry.endsWith(".json")).sort()) {
    const manifestPath = join(manifestsDirectory, name);
    // The sidecar itself must live inside .mesh2threejs/derived/.
    if (relative(manifestsDirectory, manifestPath).startsWith("..")) continue;
    let value: unknown;
    try {
      value = JSON.parse(await readFile(manifestPath, "utf8"));
    } catch {
      continue;
    }
    if (!isDerivationManifest(value)) continue;
    const manifest = value as DerivationManifest;
    if (!DERIVED_OPERATORS.has(manifest.operator)) continue;
    if (!allowedPhases.has(manifest.phase)) continue;
    // Canonical path/filename consistency: model/.generated/<phase>.mjs exactly.
    if (manifest.generatedModulePath !== `model/.generated/${manifest.phase}.mjs`) continue;

    // Generated path must be relative and resolve strictly inside model/.generated/.
    if (isAbsolute(manifest.generatedModulePath) || manifest.generatedModulePath.includes("..")) continue;
    const modulePath = resolve(workspaceRoot, manifest.generatedModulePath);
    const relation = relative(canonicalGeneratedRoot, modulePath);
    if (!relation || relation.startsWith("..") || isAbsolute(relation)) continue;

    if (manifest.oraclePreparationIdentity !== preparationIdentity) continue;

    // Durable state authority: binding must exist for the CANONICAL workspace-relative key.
    const bindingKey = manifest.generatedModulePath.replaceAll("\\", "/");
    const binding = bindings[bindingKey];
    if (!binding) continue;
    if (binding.oraclePreparationIdentity !== preparationIdentity) continue;
    const computedManifestHash = derivationManifestHash(manifest);
    if (binding.manifestHash !== computedManifestHash) continue;

    let bytes: Buffer;
    try {
      bytes = await readFile(modulePath);
    } catch {
      continue;
    }
    const moduleHash = sha256(bytes);
    if (moduleHash !== manifest.generatedModuleHash || moduleHash !== binding.generatedModuleHash) continue;

    trusted.set(modulePath, { manifestPath, manifestHash: computedManifestHash, manifest });
  }
  return trusted;
}

/** Lists phases that currently have an agent-owned declarative repair spec on disk (`model/repairs/<phase>.json`). */
export async function discoverRepairs(workspaceRoot: string): Promise<RepairModuleReference[]> {
  const directory = resolve(workspaceRoot, REPAIRS_DIRECTORY);
  let names: string[] = [];
  try {
    names = await readdir(directory);
  } catch {
    return [];
  }
  return names.filter((name) => name.endsWith(".json")).sort().map((name) => ({ phase: name.replace(/\.json$/u, ""), path: `${REPAIRS_DIRECTORY}/${name}` }));
}

/**
 * Trusted derived mode executes NO builder-authored code (closure plan §6.C4): any legacy
 * executable repair module is a hard failure, not an audited input.
 */
export async function assertNoExecutableRepairs(workspaceRoot: string): Promise<void> {
  const directory = resolve(workspaceRoot, REPAIRS_DIRECTORY);
  let names: string[] = [];
  try {
    names = await readdir(directory);
  } catch {
    return;
  }
  const executables = names.filter((name) => /\.(mjs|js|cjs|mts|ts)$/iu.test(name)).sort();
  if (executables.length) {
    throw new Error(`EXECUTABLE_REPAIR_NOT_ALLOWED_IN_TRUSTED_DERIVED: model/repairs carries executable modules (${executables.join(", ")}); repairs must be declarative JSON specs compiled by derive`);
  }
}

function repairBindingKey(repair: RepairModuleReference): string {
  return repair.path.replaceAll("\\", "/");
}

function repairBindingManifestHash(repair: RepairModuleReference): string {
  return sha256(canonicalJson({ kind: "repair-binding", phase: repair.phase }));
}

/**
 * Verifies the full derived lineage before any fidelity gate runs (§10.6, closure plan
 * §6.C4):
 * 1. no executable repair module exists under model/repairs (trusted derived runs execute
 *    zero builder-authored files);
 * 2. the canonical derived entry matches the trusted scaffold exactly;
 * 3. the pipeline-owned registry matches what trusted derive state regenerates;
 * 4. every locked/active derived phase has a current five-way-verified generated module;
 * 5. every present declarative repair spec is hash-bound and byte-current.
 * A forged userData marker can never substitute for any of these structural checks.
 */
export async function verifyDerivedLineage(input: {
  modelEntryPath: string;
  workspaceRoot: string;
  profile: ProfileId;
  authorshipMode: AuthorshipModeLike;
  derivedBindings: Record<string, DerivedBinding>;
  trustedModules: ReadonlyMap<string, TrustedGeneratedModule>;
  registryPath?: string;
}): Promise<void> {
  if (input.authorshipMode !== "derived") return;
  await assertNoExecutableRepairs(input.workspaceRoot);
  const entryBytes = await readFile(input.modelEntryPath, "utf8");
  if (entryBytes !== MODEL_DERIVED_SCAFFOLD) {
    throw new Error("derived lineage violation: the canonical derived model entry was replaced or edited; restore the pipeline-owned scaffold");
  }
  const boundPhases = Object.keys(input.derivedBindings)
    .filter((key) => key.startsWith(`${GENERATED_DIRECTORY}/`) && key.endsWith(".mjs"))
    .map((key) => key.slice(GENERATED_DIRECTORY.length + 1, -".mjs".length));
  const orderedBound = input.profile === "tank"
    ? ["hull", "turret", "gun", "running-gear", "tracks"].filter((phase) => boundPhases.includes(phase))
    : [...boundPhases].sort();
  const repairs = await discoverRepairs(input.workspaceRoot);
  const expectedRegistry = generateRegistrySource(input.profile, orderedBound);
  const registryPath = input.registryPath ?? resolve(input.workspaceRoot, GENERATED_REGISTRY_PATH);
  let registryBytes: string;
  try {
    registryBytes = await readFile(registryPath, "utf8");
  } catch {
    throw new Error("derived lineage violation: the pipeline-owned generated registry is missing");
  }
  if (registryBytes !== expectedRegistry) {
    throw new Error("derived lineage violation: the generated registry does not match trusted derive state; rerun derive instead of editing it");
  }
  for (const phase of orderedBound) {
    const key = `${GENERATED_DIRECTORY}/${phase}.mjs`;
    if (!input.derivedBindings[key]) throw new Error(`derived lineage violation: phase ${phase} lacks a durable generated binding`);
    const modulePath = resolve(input.workspaceRoot, key);
    if (!input.trustedModules.has(modulePath)) {
      throw new Error(`derived lineage violation: generated module for phase ${phase} fails five-way authority verification (stale, unbound, or tampered)`);
    }
  }
  for (const repair of repairs) {
    const binding = input.derivedBindings[repairBindingKey(repair)];
    const livePath = resolve(input.workspaceRoot, repair.path);
    let liveHash: string;
    try {
      liveHash = sha256(await readFile(livePath));
    } catch {
      throw new Error(`derived lineage violation: derive state references missing repair spec ${repair.path}`);
    }
    // The live spec bytes must hash to the recorded spec hash AND compile cleanly against
    // its own phase so malformed or tampered data fails before candidate execution.
    if (!binding || binding.generatedModuleHash !== liveHash || binding.manifestHash !== repairBindingManifestHash(repair)) {
      throw new Error(`derived lineage violation: repair spec ${repair.path} is unbound or stale; rerun derive`);
    }
  }
}

/** Binds a validated declarative repair spec into the durable derivation bindings. */
export function repairBinding(repair: RepairModuleReference, specHash: string, oraclePreparationIdentity: string): DerivedBinding {
  return { manifestHash: repairBindingManifestHash(repair), generatedModuleHash: specHash, oraclePreparationIdentity };
}

type AuthorshipModeLike = "derived" | "independent";

export async function fileExists(path: string): Promise<boolean> {
  try { await stat(path); return true; } catch { return false; }
}
