import { readFile, readdir } from "node:fs/promises";
import { isAbsolute, join, relative, resolve } from "node:path";
import { canonicalJson, sha256 } from "./hashing.js";
import type { DerivedBinding } from "./state.js";
import type { ProfileId } from "../types.js";

const DERIVED_OPERATORS = new Set(["mesh-simplify", "radial-fit", "course-regenerate", "axis-fit"]);

/** Canonical workspace-relative directory of generated phase modules. */
export const GENERATED_DIRECTORY = "model/.generated";
/** Pipeline-owned composition layer regenerated from current derivations; never agent-edited. */
export const GENERATED_REGISTRY_PATH = `${GENERATED_DIRECTORY}/registry.mjs`;

/**
 * Tank articulation doctrine baked into the composition layer: the gun pivot rides under the
 * turret pivot so turretYaw physically carries the gun, matching the profile contract's
 * moving/stationary sets. Kept declarative and profile-scoped rather than name-guessed at
 * runtime across arbitrary subjects.
 */
const PROFILE_PIVOT_NESTING: Record<ProfileId, ReadonlyArray<readonly [string, string]>> = {
  tank: [["gun-pivot", "turret-pivot"]],
  generic: [],
};

const PROFILE_POSE_CONTROLS: Record<ProfileId, string> = {
  tank: [
    `      const turretPivot = root.getObjectByName("turret-pivot");`,
    `      if (turretPivot) turretPivot.rotation.y = p.turretYaw ?? 0;`,
    `      const gunPivot = root.getObjectByName("gun-pivot");`,
    `      if (gunPivot) gunPivot.rotation.x = p.gunElevation ?? 0;`,
  ].join("\n"),
  generic: "",
};

/**
 * Deterministically regenerates the pipeline-owned registry module from the currently bound
 * derived phases, given in profile dependency order. The authored entry imports this module
 * exactly once, so later derivations rewire automatically without touching agent files.
 */
export function generateRegistrySource(profile: ProfileId, orderedPhases: ReadonlyArray<string>): string {
  const identifier = (phase: string): string => `createSeed${phase.replace(/[^a-z0-9]+/giu, "")}`;
  const lines: string[] = [];
  lines.push(`// Generated by mesh2threejs derive — trusted pipeline composition layer (do not edit by hand).`);
  lines.push(`import * as THREE from "three";`);
  for (const phase of orderedPhases) lines.push(`import { createSeed as ${identifier(phase)} } from "./${phase}.mjs";`);
  lines.push(``);
  lines.push(`function isDescendantOf(node, ancestor) {`);
  lines.push(`  let current = node.parent;`);
  lines.push(`  while (current) {`);
  lines.push(`    if (current === ancestor) return true;`);
  lines.push(`    current = current.parent;`);
  lines.push(`  }`);
  lines.push(`  return false;`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`const PIVOT_NESTING = [`);
  for (const [child, parent] of PROFILE_PIVOT_NESTING[profile]) lines.push(`  [${JSON.stringify(child)}, ${JSON.stringify(parent)}],`);
  lines.push(`];`);
  lines.push(``);
  lines.push(`export function createGeneratedCandidate() {`);
  lines.push(`  const root = new THREE.Group();`);
  lines.push(`  root.name = "candidate";`);
  for (const phase of orderedPhases) lines.push(`  root.add(${identifier(phase)}());`);
  lines.push(`  // World-preserving reparent: seed modules emit pivots at WORLD coordinates, so`);
  lines.push(`  // nesting a child pivot under its articulated parent must rebase the local`);
  lines.push(`  // position by the parent's world origin or the geometry shifts and fails gates.`);
  lines.push(`  const childWorld = new THREE.Vector3();`);
  lines.push(`  const parentWorld = new THREE.Vector3();`);
  lines.push(`  for (const [childName, parentName] of PIVOT_NESTING) {`);
  lines.push(`    const child = root.getObjectByName(childName);`);
  lines.push(`    const parent = root.getObjectByName(parentName);`);
  lines.push(`    if (!child || !parent || child === parent) continue;`);
  lines.push(`    if (isDescendantOf(child, parent)) continue;`);
  lines.push(`    child.getWorldPosition(childWorld);`);
  lines.push(`    if (child.parent) child.removeFromParent();`);
  lines.push(`    parent.add(child);`);
  lines.push(`    parent.getWorldPosition(parentWorld);`);
  lines.push(`    child.position.set(childWorld.x - parentWorld.x, childWorld.y - parentWorld.y, childWorld.z - parentWorld.z);`);
  lines.push(`  }`);
  lines.push(`  return {`);
  lines.push(`    root,`);
  lines.push(`    setPose(pose) {`);
  lines.push(`      const p = pose ?? {};`);
  if (PROFILE_POSE_CONTROLS[profile]) lines.push(PROFILE_POSE_CONTROLS[profile]);
  lines.push(`    },`);
  lines.push(`  };`);
  lines.push(`}`);
  lines.push(``);
  return lines.join("\n");
}

/** Registry bytes for a fresh derived workspace with no derived phases yet. */
export function emptyGeneratedRegistry(profile: ProfileId): string {
  return generateRegistrySource(profile, []);
}

/**
 * Pipeline-owned provenance for one generated seed module. A manifest is candidate
 * provenance/configuration, not certification evidence: it exists so the audit can tell
 * trusted pipeline-generated geometry apart from hand-authored payloads, and so stale or
 * tampered artifacts fail closed against the current oracle preparation.
 */
export interface DerivationManifest {
  schemaVersion: 1;
  kind: "mesh2threejs-derived-seed";
  phase: string;
  oraclePreparationIdentity: string;
  preparedOracleHash: string;
  operator: "mesh-simplify" | "radial-fit" | "course-regenerate" | "axis-fit";
  recipe: Record<string, unknown>;
  inputGeometryHash: string;
  outputGeometryHash: string;
  /** Workspace-relative path of the generated module this manifest binds. */
  generatedModulePath: string;
  generatedModuleHash: string;
  inputTriangles: number;
  outputTriangles: number;
  /** Relative geometric error reported by the simplifier for the selected tier. */
  simplifierError?: number;
}

/** Workspace directory holding derivation manifests, keyed one per generated module. */
export function derivedDirectory(internalRoot: string): string {
  return join(internalRoot, "derived");
}

export function derivationManifestHash(manifest: DerivationManifest): string {
  return sha256(canonicalJson(manifest));
}

function isDerivationManifest(value: unknown): value is DerivationManifest {
  if (!value || typeof value !== "object" || Array.isArray(value)) return false;
  const manifest = value as Partial<DerivationManifest>;
  return manifest.schemaVersion === 1
    && manifest.kind === "mesh2threejs-derived-seed"
    && typeof manifest.phase === "string"
    && typeof manifest.oraclePreparationIdentity === "string"
    && typeof manifest.preparedOracleHash === "string"
    && typeof manifest.operator === "string"
    && typeof manifest.inputGeometryHash === "string"
    && typeof manifest.outputGeometryHash === "string"
    && typeof manifest.generatedModulePath === "string"
    && typeof manifest.generatedModuleHash === "string"
    && Number.isFinite(manifest.inputTriangles)
    && Number.isFinite(manifest.outputTriangles);
}

export interface TrustedGeneratedModule {
  manifestPath: string;
  manifestHash: string;
  manifest: DerivationManifest;
}

export interface TrustedModuleAuthorityInput {
  /** Directory containing candidate derivation manifests (`<ws>/.mesh2threejs/derived`). */
  directory: string;
  workspaceRoot: string;
  /** Canonical preparation identity currently bound in workspace state. */
  preparationIdentity: string;
  /** Durable `state.derivedBindings`, written only by trusted derive code. */
  bindings: Record<string, DerivedBinding>;
  /** Builder phases for which a manifest may exist. */
  allowedPhases: ReadonlySet<string>;
}

/**
 * Loads every derivation manifest under `<workspace>/.mesh2threejs/derived` that carries FULL
 * five-way authority. A sidecar alone is not authority; all of the following must agree:
 *
 * 1. structurally valid manifest with a known operator;
 * 2. phase is a valid builder phase and module filename matches it canonically;
 * 3. generated path is workspace-relative AND resolves inside `<ws>/model/.generated/`
 *    (no absolute paths, no `..` or symlink escape);
 * 4. `oraclePreparationIdentity` equals the CURRENT bound preparation;
 * 5. durable state binding exists for the canonical module path, its manifest hash equals
 *    the recomputed manifest hash, its generated-module hash equals both the manifest's and
 *    the live file bytes', and its preparation identity equals the current one.
 *
 * Anything else is ordinary candidate source and receives the normal topology-dump audit.
 */
export async function loadTrustedGeneratedModules(input: TrustedModuleAuthorityInput): Promise<Map<string, TrustedGeneratedModule>> {
  const { directory, workspaceRoot, preparationIdentity, bindings, allowedPhases } = input;
  const trusted = new Map<string, TrustedGeneratedModule>();
  const canonicalGeneratedRoot = resolve(workspaceRoot, "model/.generated");
  let names: string[];
  try {
    names = await readdir(directory);
  } catch {
    return trusted;
  }
  const manifestsDirectory = resolve(directory);
  for (const name of names.filter((entry) => entry.endsWith(".json")).sort()) {
    const manifestPath = join(manifestsDirectory, name);
    // The sidecar itself must live inside .mesh2threejs/derived/.
    if (relative(manifestsDirectory, manifestPath).startsWith("..")) continue;
    let value: unknown;
    try {
      value = JSON.parse(await readFile(manifestPath, "utf8"));
    } catch {
      continue;
    }
    if (!isDerivationManifest(value)) continue;
    const manifest = value as DerivationManifest;
    if (!DERIVED_OPERATORS.has(manifest.operator)) continue;
    if (!allowedPhases.has(manifest.phase)) continue;
    // Canonical path/filename consistency: model/.generated/<phase>.mjs exactly.
    if (manifest.generatedModulePath !== `model/.generated/${manifest.phase}.mjs`) continue;

    // Generated path must be relative and resolve strictly inside model/.generated/.
    if (isAbsolute(manifest.generatedModulePath) || manifest.generatedModulePath.includes("..")) continue;
    const modulePath = resolve(workspaceRoot, manifest.generatedModulePath);
    const relation = relative(canonicalGeneratedRoot, modulePath);
    if (!relation || relation.startsWith("..") || isAbsolute(relation)) continue;

    if (manifest.oraclePreparationIdentity !== preparationIdentity) continue;

    // Durable state authority: binding must exist for the CANONICAL workspace-relative key.
    const bindingKey = manifest.generatedModulePath.replaceAll("\\", "/");
    const binding = bindings[bindingKey];
    if (!binding) continue;
    if (binding.oraclePreparationIdentity !== preparationIdentity) continue;
    const computedManifestHash = derivationManifestHash(manifest);
    if (binding.manifestHash !== computedManifestHash) continue;

    let bytes: Buffer;
    try {
      bytes = await readFile(modulePath);
    } catch {
      continue;
    }
    const moduleHash = sha256(bytes);
    if (moduleHash !== manifest.generatedModuleHash || moduleHash !== binding.generatedModuleHash) continue;

    trusted.set(modulePath, { manifestPath, manifestHash: computedManifestHash, manifest });
  }
  return trusted;
}
