import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type * as THREE from "three";
import { canonicalJson, sha256 } from "./hashing.js";
import { snapshotScene } from "./geometry.js";
import type { OraclePreparationBinding } from "./oracle.js";
import { ConstructionRoutingError } from "./construction-mode.js";

/**
 * Oracle ReferenceScene (stylized-authored mode design §11). A trusted, read-only Three.js
 * representation of the prepared oracle, generated by trusted code from the SAME prepared
 * oracle the deterministic evaluation consumes — identical canonical frame, normalization,
 * pivots, semantics, and world transforms. It exists purely for visual comparison and
 * measurement: candidate compilation NEVER receives it (design invariant 2, §11.3).
 */

export const REFERENCE_SCENE_SCHEMA_VERSION = 1;
export const REFERENCE_VIEW_DIRECTORY = ".mesh2threejs/reference-view";

export interface ReferenceSceneComponent {
  semanticId: string;
  parentSemanticId?: string;
  origin?: [number, number, number];
  bounds: { min: [number, number, number]; max: [number, number, number]; size: [number, number, number]; center: [number, number, number] };
  /** Full source geometry retained for viewing; consumers must never feed it to a candidate. */
  trianglePositions: number[];
  triangleCount: number;
}

export interface ReferenceScene {
  schemaVersion: 1;
  kind: "mesh2threejs-oracle-reference-scene";
  oraclePreparationIdentity: string;
  sourceHash: string;
  metadata: { name: string; forwardAxis?: string };
  meshCount: number;
  materialCount: number;
  triangleCount: number;
  components: ReferenceSceneComponent[];
}

export interface ReferenceSceneManifest {
  schemaVersion: 1;
  kind: "mesh2threejs-oracle-reference-scene-manifest";
  oraclePreparationIdentity: string;
  sourceHash: string;
  serializationVersion: string;
  referenceSceneHash: string;
  referenceSceneFile: string;
}

export function referenceSceneHash(scene: ReferenceScene): string {
  return sha256(canonicalJson(scene));
}

export function referenceViewDirectory(internalRoot: string): string {
  return join(internalRoot, "reference-view");
}

/**
 * Builds the read-only reference scene from the LIVE prepared oracle group. Uses the same
 * snapshot pipeline as deterministic evaluation, so bounds/origins/frame match evaluator
 * truth exactly (design §33.4).
 */
export function buildReferenceScene(oracle: THREE.Group, binding: OraclePreparationBinding): ReferenceScene {
  const snapshot = snapshotScene(oracle);
  const components: ReferenceSceneComponent[] = Object.values(snapshot.components)
    .sort((a, b) => a.id.localeCompare(b.id))
    .map((component) => {
      const triangleIndices = component.triangleIndices;
      const positions = snapshot.triangleData.positions;
      const values: number[] = [];
      for (let index = 0; index < triangleIndices.length; index += 1) {
        const base = triangleIndices[index]! * 9;
        for (let axis = 0; axis < 9; axis += 1) values.push(Number(positions[base + axis]!.toFixed(6)));
      }
      return {
        semanticId: component.id,
        ...(component.parentSemanticId ? { parentSemanticId: component.parentSemanticId } : {}),
        ...(component.origin ? { origin: [component.origin[0], component.origin[1], component.origin[2]] as [number, number, number] } : {}),
        bounds: {
          min: component.bounds.min,
          max: component.bounds.max,
          size: component.bounds.size,
          center: component.bounds.center,
        },
        trianglePositions: values,
        triangleCount: triangleIndices.length,
      };
    });
  return {
    schemaVersion: REFERENCE_SCENE_SCHEMA_VERSION,
    kind: "mesh2threejs-oracle-reference-scene",
    oraclePreparationIdentity: binding.identity,
    sourceHash: binding.sourceHash,
    metadata: { name: snapshot.metadata.name, ...(snapshot.metadata.forwardAxis ? { forwardAxis: snapshot.metadata.forwardAxis } : {}) },
    meshCount: snapshot.meshCount,
    materialCount: snapshot.materialCount,
    triangleCount: snapshot.triangleCount,
    components,
  };
}

/** Persists the reference scene + manifest atomically into `.mesh2threejs/reference-view/`. */
export async function writeReferenceScene(internalRoot: string, scene: ReferenceScene): Promise<ReferenceSceneManifest> {
  const directory = referenceViewDirectory(internalRoot);
  await mkdir(directory, { recursive: true });
  const scenePath = join(directory, "oracle-scene.json");
  const temporary = `${scenePath}.${process.pid}.tmp`;
  await writeFile(temporary, `${JSON.stringify(scene, null, 2)}\n`, { flag: "wx" });
  await rename(temporary, scenePath);
  const manifest: ReferenceSceneManifest = {
    schemaVersion: 1,
    kind: "mesh2threejs-oracle-reference-scene-manifest",
    oraclePreparationIdentity: scene.oraclePreparationIdentity,
    sourceHash: scene.sourceHash,
    serializationVersion: "1.0.0",
    referenceSceneHash: referenceSceneHash(scene),
    referenceSceneFile: ".mesh2threejs/reference-view/oracle-scene.json",
  };
  await writeFile(join(directory, "manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`, { flag: "wx" });
  return manifest;
}

export interface LoadedReferenceScene {
  scene: ReferenceScene;
  manifest: ReferenceSceneManifest;
  /** Content hash of the live scene file. */
  fileHash: string;
}

/**
 * Loads the cached reference scene and verifies it against the CURRENT bound preparation
 * (design §33.4): same preparation identity, same source hash, intact manifest, live bytes
 * matching the recorded scene hash. Anything stale throws REFERENCE_SCENE_STALE.
 */
export async function loadReferenceScene(internalRoot: string, currentPreparation: OraclePreparationBinding): Promise<LoadedReferenceScene> {
  const directory = referenceViewDirectory(internalRoot);
  let manifestValue: unknown;
  try {
    manifestValue = JSON.parse(await readFile(join(directory, "manifest.json"), "utf8"));
  } catch {
    throw new ConstructionRoutingError("REFERENCE_SCENE_STALE", "no reference scene has been generated for the current oracle preparation; run the reference-scene operation");
  }
  const manifest = manifestValue as ReferenceSceneManifest;
  if (manifest.kind !== "mesh2threejs-oracle-reference-scene-manifest" || manifest.schemaVersion !== 1) {
    throw new ConstructionRoutingError("REFERENCE_SCENE_STALE", "reference scene manifest is invalid");
  }
  if (manifest.oraclePreparationIdentity !== currentPreparation.identity) {
    throw new ConstructionRoutingError("REFERENCE_SCENE_STALE", `reference scene was generated for preparation ${manifest.oraclePreparationIdentity}, but the bound preparation is ${currentPreparation.identity}; regenerate it`);
  }
  // The scene file always lives at the canonical reference-view path; the manifest path field
  // is provenance only and is checked to match it.
  if (manifest.referenceSceneFile.replaceAll("\\", "/") !== ".mesh2threejs/reference-view/oracle-scene.json") {
    throw new ConstructionRoutingError("REFERENCE_SCENE_STALE", `reference scene manifest points outside the canonical reference-view path: ${manifest.referenceSceneFile}`);
  }
  let sceneValue: unknown;
  try {
    sceneValue = JSON.parse(await readFile(join(directory, "oracle-scene.json"), "utf8"));
  } catch (error) {
    throw new ConstructionRoutingError("REFERENCE_SCENE_STALE", `reference scene file is missing or unreadable: ${error instanceof Error ? error.message : String(error)}`);
  }
  const scene = sceneValue as ReferenceScene;
  if (scene.kind !== "mesh2threejs-oracle-reference-scene" || scene.schemaVersion !== REFERENCE_SCENE_SCHEMA_VERSION) {
    throw new ConstructionRoutingError("REFERENCE_SCENE_STALE", "reference scene payload is invalid");
  }
  if (scene.oraclePreparationIdentity !== currentPreparation.identity || scene.sourceHash !== currentPreparation.sourceHash) {
    throw new ConstructionRoutingError("REFERENCE_SCENE_STALE", "reference scene payload contradicts the current oracle preparation; regenerate it");
  }
  const fileHash = referenceSceneHash(scene);
  if (fileHash !== manifest.referenceSceneHash) {
    throw new ConstructionRoutingError("REFERENCE_SCENE_STALE", "reference scene bytes changed after generation; regenerate it");
  }
  return { scene, manifest, fileHash };
}

/**
 * Alignment proof (design §33.4): the reference scene must agree with the evaluator's view
 * of the prepared oracle for scene fingerprint, bounds, and semantic origins.
 */
export function verifyReferenceSceneAlignment(scene: ReferenceScene, oracle: THREE.Group): { aligned: boolean; problems: string[] } {
  const problems: string[] = [];
  const snapshot = snapshotScene(oracle);
  if (scene.triangleCount !== snapshot.triangleCount) problems.push(`triangle count ${scene.triangleCount} != evaluator ${snapshot.triangleCount}`);
  if (scene.meshCount !== snapshot.meshCount) problems.push(`mesh count ${scene.meshCount} != evaluator ${snapshot.meshCount}`);
  const evaluatorComponents = Object.values(snapshot.components);
  for (const component of evaluatorComponents) {
    const reference = scene.components.find((item) => item.semanticId === component.id);
    if (!reference) { problems.push(`semantic ${component.id} missing from reference scene`); continue; }
    const same = (a: readonly number[], b: readonly number[]): boolean => a.every((value, index) => Math.abs(value - b[index]!) < 1e-6);
    if (!same(reference.bounds.min, component.bounds.min) || !same(reference.bounds.max, component.bounds.max)) problems.push(`semantic ${component.id} bounds disagree with evaluator`);
    if (component.origin && (!reference.origin || !same(reference.origin, component.origin))) problems.push(`semantic ${component.id} origin disagrees with evaluator`);
  }
  const live = buildReferenceScene(oracle, { identity: scene.oraclePreparationIdentity, sourceHash: scene.sourceHash, preparedHash: "" } as OraclePreparationBinding);
  if (referenceSceneHash(live) !== referenceSceneHash(scene)) problems.push("reference scene is not reproducible from the live prepared oracle");
  return { aligned: problems.length === 0, problems };
}

